### ISSUE TITLE
Munin plugins not working

### ISSUE THREAD

**Issue by viktorsmari** [adafruit/Adafruit_Python_BMP#10]
When testing the munin plugin:
`python munin/i2c_pressure`

I get the error:

  File "munin/i2c_pressure", line 4, in <module>
    from Adafruit_BMP085 import BMP085
ImportError: No module named Adafruit_BMP085

Is there a quick fix for this? I would really like to intergrate this to munin.

**Comment by ladyada** [comment]
hiya we're closing these issues and archiving this repo because this library has been deprecated!

the bmp085 and bmp180 are no longer made, and are replaced by the bmp280 + friends

we are now only using our circuitpython sensor libraries in python

check out this guide for using the bmp280 with python!
https://learn.adafruit.com/adafruit-bmp280-barometric-pressure-plus-temperature-sensor-breakout
