### ISSUE TITLE
Release to PyPI

### ISSUE THREAD

**Issue by JokerQyou** [adafruit/Adafruit_Python_BMP#15]
Could you kindly release this library to PyPI so users can easily install it via `pip install` command?

**Comment by ladyada** [comment]
hiya we're closing these issues and archiving this repo because this library has been deprecated!

the bmp085 and bmp180 are no longer made, and are replaced by the bmp280 + friends

we are now only using our circuitpython sensor libraries in python

check out this guide for using the bmp280 with python!
https://learn.adafruit.com/adafruit-bmp280-barometric-pressure-plus-temperature-sensor-breakout
