### ISSUE TITLE
Update examples/google_spreadsheet.py to use oAuth2

### ISSUE THREAD

**Issue by natoe33** [adafruit/Adafruit_Python_BMP#16]
Error received while running examples/google_spreadsheet.py:

```
Logging sensor measurements to temp_log every 30 seconds.
Press Ctrl-C to quit.
/usr/local/lib/python2.7/dist-packages/gspread/client.py:73: Warning:
            ClientLogin is deprecated:
            https://developers.google.com/identity/protocols/AuthForInstalledApps?csw=1

            Authorization with email and password will stop working on April 20, 2015.

            Please use oAuth2 authorization instead:
            http://gspread.readthedocs.org/en/latest/oauth2.html


  """, Warning)
Unable to login and get spreadsheet.  Check email, password, spreadsheet name.
```

**Comment by ladyada** [comment]
hiya we're closing these issues and archiving this repo because this library has been deprecated!

the bmp085 and bmp180 are no longer made, and are replaced by the bmp280 + friends

we are now only using our circuitpython sensor libraries in python

check out this guide for using the bmp280 with python!
https://learn.adafruit.com/adafruit-bmp280-barometric-pressure-plus-temperature-sensor-breakout
