### ISSUE TITLE
Build on Banana PI did not work

### ISSUE THREAD

**Issue by ds2k5** [adafruit/Adafruit_Python_BMP#18]
Hello,
using a Banana PI with Debian 8.6.

**git clone https://github.com/adafruit/Adafruit_Python_BMP
cd Adafruit_Python_BMP
sudo python3 setup.py install**

compilation terminated.
error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

[build.txt](https://github.com/adafruit/Adafruit_Python_BMP/files/671735/build.txt)

arm-linux-gnueabihf-gcc (Debian 4.9.2-10) 4.9.2

How to fix this ?

**Comment by ds2k5** [comment]
after i installed: sudo apt-get install python3-dev
got a next step
but it did not work

cd ~/Adafruit_Python_BMP/examples

udo i2cdetect -y 2
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- 77

**Comment by compasss** [comment]
i got the same problem with my orangepi pc
change `sensor=BMP085.BMP085()` to `sensor = BMP085.BMP085(busnum=0)`
it works

**Comment by ladyada** [comment]
hiya we're closing these issues and archiving this repo because this library has been deprecated!

the bmp085 and bmp180 are no longer made, and are replaced by the bmp280 + friends

we are now only using our circuitpython sensor libraries in python

check out this guide for using the bmp280 with python!
https://learn.adafruit.com/adafruit-bmp280-barometric-pressure-plus-temperature-sensor-breakout
