### ISSUE TITLE
Raspbian install error and related issues

### ISSUE THREAD

**Issue by sarnold** [adafruit/Adafruit_Python_BMP#3]
Hi:  I got this to work once, but now fails weirdly due to the setup.py file and the non-standard (and somewhat hacky) Raspbian python environment.  I'm still trying to replicate the "working" part using your sensor module, and the reason I had to install it again is because the other Python sensor code (which also worked fine) stopped working after I installed _your_ Python modules for the BMP sensor.  The sensor board I'm working with has three sensors integrated (SHT10, BMP085, and MPU6050) but the required Python modules break each other when the upstream "install" is run.  Proper packaging as *.debs would avoid all of this pip/easy_install nonsense, which turns out to be anything but easy.  I'm through debugging this stuff for now and I will make some proper git/versioned ebuilds for what I need (conference deadlines are approaching fast) and put them in our arm testing overlay (I do Gentoo and Yocto, which is plenty enough already).  Please consider packaging an actual release of your modules and either package the dependencies or push it up to Raspbian and get them to do it.  It's currently not possible for an OS/distribution developer to install multiple sensor modules in the latest 09-09 Raspbian using the available tools/docs (such as they are) so I really don't see how a "normal" user could do it.

**Comment by ladyada** [comment]
hiya we're closing these issues and archiving this repo because this library has been deprecated!

the bmp085 and bmp180 are no longer made, and are replaced by the bmp280 + friends

we are now only using our circuitpython sensor libraries in python

check out this guide for using the bmp280 with python!
https://learn.adafruit.com/adafruit-bmp280-barometric-pressure-plus-temperature-sensor-breakout
